#!/bin/bash
composer self-update

if [ ! "$(ls -A /data/http)" ]
then
    # Give core user a home
    usermod -d /data core
    # and a shell
    usermod -s /bin/bash core
    # and a .ssh folder
    mkdir -p /data/.ssh
    mkdir -p /data/secure/ssh
    cp -R /config/config/* /data/config
    rm /etc/nginx/conf.d/02cache.conf
    cd /data/http
    git clone -b $ROADIZ_BRANCH https://github.com/roadiz/roadiz.git ./
    composer install -n --no-dev -o
    cp conf/config.default.yml conf/config.yml
    chown -R core:core /data
    chmod 0770 /data/secure
    chmod 0700 /data/.ssh
else
    # Update dependencies
    # and empty roadiz cache
    cd /data/http
    composer update -n --no-dev -o
    chown -R core:core /data
    chmod 0770 /data/secure
    chmod 0700 /data/.ssh
    bin/roadiz cache --clear-all
fi
